### PR TITLE
Update intro

### PR DESCRIPTION
**Pull request by agnessnowplow**
This is to update the introduction section as proposed by Etien.

### CODE REVIEW

**Review by Jack-Keene — APPROVED** [review]
LGTM!

**Review by emielver — APPROVED** [review]
LGTM

**Comment by emielver** [comment]
Actually Agnes while you're at it could we replace instances of `ecommerce` with `e-commerce`?

**Review by emielver — APPROVED** [review]
Looks great, thanks so much!

**Comment by agnessnowplow** [comment]
It always bothered me, it looks cleaner!

**Pull request merged**
